
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JELOUANE_TRAVAUX_Application_By_JELOUANE_Alale
{

using System;
    using System.Collections.Generic;
    
public partial class AppSetting
{

    public int id_s { get; set; }

    public string Theme { get; set; }

    public string appLang { get; set; }

    public string Keylang { get; set; }

    public Nullable<bool> SaveLoginInfo { get; set; }

}

}
