//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JELOUANE_TRAVAUX_Application_By_JELOUANE_Alale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiel
    {
        public int Id_Materiel { get; set; }
        public string Nom_Materiel { get; set; }
        public byte[] Photo_Materiel { get; set; }
        public string Color_Materiel { get; set; }
        public string Genre_Materiel { get; set; }
        public string Fondateur_Materiel { get; set; }
        public Nullable<int> Quantity_Materiel { get; set; }
        public Nullable<int> Price_materiel { get; set; }
    }
}
