//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JELOUANE_TRAVAUX_Application_By_JELOUANE_Alale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materiel()
        {
            this.Utilisers = new HashSet<Utiliser>();
        }
    
        public int Id_Materiel { get; set; }
        public string Nom_Materiel { get; set; }
        public byte[] Photo_Materiel { get; set; }
        public string Color_Materiel { get; set; }
        public string Genre_Materiel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utiliser> Utilisers { get; set; }
    }
}
