//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JELOUANE_TRAVAUX_Application_By_JELOUANE_Alale
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JELOUANE_TRAVAUXEntities2 : DbContext
    {
        public JELOUANE_TRAVAUXEntities2()
            : base("name=JELOUANE_TRAVAUXEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Materiel> Materiels { get; set; }
        public virtual DbSet<Mur> Murs { get; set; }
        public virtual DbSet<projet> projets { get; set; }
        public virtual DbSet<Salle> Salles { get; set; }
        public virtual DbSet<utilisateur> utilisateurs { get; set; }
        public virtual DbSet<Utiliser> Utilisers { get; set; }
    }
}
