//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JELOUANE_TRAVAUX_Application_By_JELOUANE_Alale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mur
    {
        public int ID_Mur { get; set; }
        public Nullable<int> Numero_Mur { get; set; }
        public Nullable<int> Longeur_Mur { get; set; }
        public Nullable<int> Largeur_Mur { get; set; }
        public string couleur_Mur_AV { get; set; }
        public string couleur_Mur_AP { get; set; }
        public Nullable<int> Id_Salle { get; set; }
    
        public virtual Salle Salle { get; set; }
    }
}
