
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JELOUANE_TRAVAUX_Application_By_JELOUANE_Alale
{

using System;
    using System.Collections.Generic;
    
public partial class Notification
{

    public int id_notification { get; set; }

    public Nullable<int> id_Project { get; set; }

    public string message_notification { get; set; }

    public string type_notification { get; set; }

    public Nullable<bool> visibility { get; set; }



    public virtual projet projet { get; set; }

}

}
