
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JELOUANE_TRAVAUX_Application_By_JELOUANE_Alale
{

using System;
    using System.Collections.Generic;
    
public partial class Salle
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Salle()
    {

        this.Murs = new HashSet<Mur>();

    }


    public int Id_Salle { get; set; }

    public string Nom_Salle { get; set; }

    public Nullable<int> ID_Projet { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Mur> Murs { get; set; }

    public virtual projet projet { get; set; }

}

}
